//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ecommerce_Project.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrderAddress
    {
        public int AddressID { get; set; }
        public int OrderID { get; set; }
        public string BillingAddress { get; set; }
        public string ShippingAddress { get; set; }
    
        public virtual Order Order { get; set; }
    }
}
